Generated IPC Swift complies with linter https://bugs.webkit.org/show_bug.cgi?id=311916 rdar://174477093
Reviewed by Richard Robinson.

The Swift code generated for IPC message handlers by messages.py previously
resulted in linter warnings such as

Source/WebKit/Scripts/webkit/tests/TestWithSwiftMessageReceiver.swift:25:23: error: [RemoveLine] remove line break
Source/WebKit/Scripts/webkit/tests/TestWithSwiftMessageReceiver.swift:51:2: error: [RemoveLine] remove line break

Fix those by removing the extra blank lines. This also inlines a function
within messages.py. Previously, generate_swift_message_handler_internals was a
separate function due to the need to call it twice to work around a Swift
problem:
https://github.com/swiftlang/swift/pull/74415

This was resolved, and the extra call to
generate_swift_message_handler_internals was already previously removed, so now
we can collapse it back into a single function.

There are no functional differences here except for the removal of the two
blank lines.

Canonical link: https://commits.webkit.org/310913@main