[GLIB] Fix RunAPITests() build.webkit.org step https://bugs.webkit.org/show_bug.cgi?id=311935
Reviewed by Aakash Jain.

This fixes the type error introduced in 310836@main:

  File "/var/buildbot/OpenSource/Tools/CISupport/build-webkit-org/steps.py", line 1117, in run
    self.command = self.shell_command(' '.join(self.command) + ' 2>&1 | python3 Tools/Scripts/filter-test-logs api')
  builtins.TypeError: sequence item 9: expected str instance, int found

* Tools/CISupport/build-webkit-org/steps.py:
(RunAPITests.run):
* Tools/CISupport/build-webkit-org/steps_unittest.py:

Canonical link: https://commits.webkit.org/310933@main